CovainfJCB/Models/Representante.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CovainfJCB.Models
{
    public class Representante
    {
        [Key]
        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name ="Identificación")]
        [MinLength(10, ErrorMessage ="Debe ingresar 10 numeros")]
        [MaxLength(10)]
        public  string Id { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [MaxLength(30)]
        public string Nombres { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [MaxLength(30)]
        public string Apellidos { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaNacimiento { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [DataType(DataType.EmailAddress)]
        public string Correo { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [MinLength(10, ErrorMessage = "Debe ingresar 10 numeros")]
        [MaxLength(10)]
        public string Celular { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [MaxLength(50)]
        public string Direccion { get; set; }

        
    }
}

CovainfJCB/Controllers/InfantesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CovainfJCB.Models;
using CovainfJCB.Data;

namespace CovainfJCB.Controllers
{
    public class InfantesController : Controller
    {

        private readonly ApplicationDbContext _context;

        public InfantesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: InfantesController
        public ActionResult Index()
        {
            IEnumerable<Infante> listInfantes = _context.Infantes;
            return View(listInfantes);
        }

        // GET: InfantesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<  CREAR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        
        // GET: InfantesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InfantesController/Create 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Infante infante )  // IFormCollection collection
        {
            if (ModelState.IsValid)
            {
                _context.Infantes.Add(infante);
                _context.SaveChanges();
            }
            return View(infante);

            //try
            //{
            //    return RedirectToAction(nameof(Index));
            //}
            //catch
            //{
            //    return View();
            //}
        }


        // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<  EDITAR >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
       
        // GET: InfantesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: InfantesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InfantesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: InfantesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        
    }
}

CovainfJCB/Controllers/RepresentantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CovainfJCB.Data;
using CovainfJCB.Models;
using Microsoft.AspNetCore.Identity;
using CovainfJCB.Views.ViewModels;

namespace CovainfJCB.Controllers
{

    public class RepresentantesController : Controller
    {

        private readonly ApplicationDbContext _context;

        public RepresentantesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Representantes
        public async Task<IActionResult> Index()
        {
            var usuario = @User.Identity.Name;
            ModeloIndex mri = new ModeloIndex();
            mri.Representante = await _context.Representantes.FirstOrDefaultAsync(m => m.Correo == usuario);
            mri.ListInfante = await _context.Infantes.ToListAsync();

            return View(mri);
            
            //return View(await _context.Representantes.ToListAsync());
        }

        // GET: Representantes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var representante = await _context.Representantes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (representante == null)
            {
                return NotFound();
            }

            return View(representante);
        }

        // GET: Representantes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Representantes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombres,Apellidos,FechaNacimiento,Correo,Celular,Direccion")] Representante representante)
        {
            if (ModelState.IsValid)
            {
                _context.Add(representante);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(representante);
        }

        // GET: Representantes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var representante = await _context.Representantes.FindAsync(id);
            if (representante == null)
            {
                return NotFound();
            }
            return View(representante);
        }

        // POST: Representantes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Nombres,Apellidos,FechaNacimiento,Correo,Celular,Direccion")] Representante representante)
        {
            if (id != representante.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(representante);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RepresentanteExists(representante.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(representante);
        }

        // GET: Representantes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var representante = await _context.Representantes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (representante == null)
            {
                return NotFound();
            }

            return View(representante);
        }

        // POST: Representantes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var representante = await _context.Representantes.FindAsync(id);
            _context.Representantes.Remove(representante);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RepresentanteExists(string id)
        {
            return _context.Representantes.Any(e => e.Id == id);
        }

       
    }
}

CovainfJCB/Views/Representantes/Create.cshtml
@model CovainfJCB.Models.Representante

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Representante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Celular" class="control-label"></label>
                <input asp-for="Celular" class="form-control" />
                <span asp-validation-for="Celular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CovainfJCB/Views/Representantes/Delete.cshtml
@model CovainfJCB.Models.Representante

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Representante</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Celular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Celular)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CovainfJCB/Views/Representantes/Details.cshtml
@model CovainfJCB.Models.Representante

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Representante</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombres)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Celular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Celular)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CovainfJCB/Views/Representantes/Edit.cshtml
@model CovainfJCB.Models.Representante

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Representante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Celular" class="control-label"></label>
                <input asp-for="Celular" class="form-control" />
                <span asp-validation-for="Celular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CovainfJCB/Views/Representantes/Index.cshtml
@*@model IEnumerable<CovainfJCB.Models.Representante>*@
@model CovainfJCB.Views.ViewModels.ModeloIndex;



@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Datos del Representante</h3>
<hr />
<br />

@{
    String Representante = "0000000000";

    if (Model.Representante != null)
    {
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Representante.Nombres)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Representante.Nombres)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Representante.Apellidos)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Representante.Apellidos)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Representante.Correo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Representante.Correo)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Representante.Celular)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Representante.Celular)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Representante.Direccion)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Representante.Direccion)
            </dd>
        </dl>
        Representante = Model.Representante.Id;
    }
    else
    {

        <a class="btn btn-success" asp-action="Create" asp-controller="Representantes">Registrar Información</a>
        <br />

    }
}



<br />

<h3>Infantes Registrados</h3>

<table class="table">
    <thead>
        <tr>
            <th>
                Identificación
            </th>
            <th>
                Nombres
            </th>
            <th>
                Apellidos
            </th>
            <th>
                Fecha Nacimiento
            </th>
        </tr>
    </thead>
    <tbody>

        @{

            if (Model.ListInfante.Count() > 0)
            {
                int encontrado = 0;
                foreach (var item in Model.ListInfante)
                {
                    if (item.IdRepresentante == Representante)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdInfante)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NombresInfante)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ApellidosInfante)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechNacimiento)
                            </td>
                        </tr>
                        encontrado = encontrado + 1;
                    }
                    if (encontrado < 1)
                    {
                        <p> No tiene Infantes registrados </p>
                    }
                }
            }

        }

    </tbody>

</table>

<a class="btn btn-success" asp-action="Create" asp-controller="Infantes">Agregar Infante</a>

@*<table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombres)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Apellidos)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FechaNacimiento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Correo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Celular)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Direccion)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @{

                int encontrado = 0;

                foreach (var item in Model)
                {
                    if (item.Correo == @User.Identity.Name)
                    {

                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombres)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Apellidos)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaNacimiento)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Celular)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Direccion)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            </td>
                        </tr>

                        encontrado = 1;

                        break;
                    }
                    if (encontrado == 1)
                    {
                        // mensaje si no lo encuentra
                    }

                }



            }


        </tbody>

    </table>*@

CovainfJCB/Views/Representantes/Representante.cshtml
@{
    ViewData["Title"] = "Representante";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Representante</h1>